imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    environment:
        php: '7.4'
        mysql: '5.7'
        # hosts:
            # laravel.dev: '127.0.0.1'
        # variables:
        #     APP_KEY: 'base64:PR8VagGyQa4jB7JELm9xg7U1C1sdJeQR5Ot1vAQJe/o='
        #     APP_ENV: 'testing'
        #     APP_URL: 'http://laravel.dev'
        #     API_HOST: 'laravel.dev'
        #     DB_HOST: '127.0.0.1'
        #     DB_DATABASE: 'laravel'
        #     DB_USERNAME: 'root'
        #     DB_PASSWORD: 'root'
        #     MAIL_DRIVER: 'log'
    nodes:
        my-tests:
            environment:
                php:
                    version: 8.1.2
    tests:
        override:
            -
                command: "make phpunit"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"