imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    environment:
        php: '7.4'
        mysql: '5.7'
        hosts:
            laravel.dev: '127.0.0.1'
        variables:
            APP_KEY: 'base64:zOltNsmgj8zCd0Bz0LkD+H9Q8pCoSq4OLPrpdLfyD6E='
            APP_ENV: 'testing'
            APP_URL: 'http://laravel.dev'
            API_HOST: 'laravel.dev'
            DB_HOST: '127.0.0.1'
            DB_DATABASE: 'scrutinizer'
            DB_USERNAME: 'root'
            DB_PASSWORD: ''
            MAIL_DRIVER: 'log'
    nodes:
        my-tests:
            environment:
                php:
                    version: 8.1.2
    tests:
        override:
            -
                command: "make phpunit"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"