imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*]

build:
  project_setup:
    override:
      - true

  nodes:
    my-tests:
      environment:
        php:
          version: 8.1.2
  tests:
    override:
      - command: "make phpunit"
        coverage:
          file: "build/coverage.clover"
          format: "php-clover"
