Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@moody94 
moody94
/
mvc-1
Public
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
mvc-1/.travis.yml
@moody94
moody94 kmom06
Latest commit b0850c9 8 days ago
 History
 1 contributor
Executable File  34 lines (27 sloc)  718 Bytes

language: php

php:
    #- "7.2"
    # - "7.4"
    # - hhvm
    - nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

sudo: false

git:
    submodules: false

before_script:
    - composer install

script:
    - php artisan test

# notifications:
#     irc: "irc.freenode.org#dbwebb"
#     urls:
        # # canax
        # - https://webhooks.gitter.im/e/6e4660b0024de67de0af
        # # canax/commons
        # - https://webhooks.gitter.im/e/dd6775c1f5b11b7421da
#     on_success: change  # options: [always|never|change] default: always
#     on_failure: always  # options: [always|never|change] default: always
#     on_start: never     # options: [always|never|change] default: always
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
You have no unread notifications