version: 2

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: cimg/php:8.1 # ...with this image as the primary container; this is where all `steps` will rundocker pull cimg/php:8.1
    working_directory: ~/laravel # directory where steps will run

    steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "composer.json" }}
                # fallback to using the latest cache if no exact match
                # is found
                - v1-dependencies-

        #- run: composer install -n --prefer-dist
        - run: make install
        - run: composer install
        - run: composer update

        - save_cache:
            paths:
                - ./vendor
            key: v1-dependencies-{{ checksum "composer.json" }}

        - run: make phpunit